### ISSUE TITLE
Adding seabreeze to bioconda?

### ISSUE THREAD

**Issue by JeanMainguy** [barricklab/seabreeze#8]
Hi,  

I think it might be nice to add `seabreeze` to Bioconda. It would make installation easier for many users.

I guess this can be trickier for a Snakemake pipeline than for a regular standalone tool, and I’m not an expert in packaging Snakemake workflows. For example, I don’t think Nextflow pipelines are usually added to Bioconda.  

That said, the Snakemake pipeline *ATLAS* is available on Bioconda:https://anaconda.org/bioconda/metagenome-atlas and it seems they made it work by wrapping the pipeline in a CLI script. Maybe that could be an option here too?

Just an idea to consider!

**Comment by ira-zibbu** [comment]
Hi @JeanMainguy ,

The authors and I had previously discussed a simple wrapper script around the Snakemake pipeline to streamline execution. It would also allow for a 'quick start' option where the user could use the CLI to directly specify a reference and query file (instead of the requirement to set up a csv file, if only one comparison was being made). This would also permit seabreeze to be added to bioconda and make installation easier.

I will implement a simple CLI wrapper around the existing pipeline.

**Comment by JeanMainguy** [comment]
Hi,

I just tried installing Seabreeze via Bioconda, and I noticed it installs an executable called `seabreeze_os_setup`. Is there a particular reason for this?

Would it be possible to have it install the main `seabreeze` executable directly, similar to what happens when running `pip install .` from the repo? That might be more intuitive for users.

Thanks!

**Comment by ira-zibbu** [comment]
Hi @JeanMainguy,

I attempted to install `seabreeze` via bioconda to replicate the issue you raised.

```
conda create --name bioconda-seabreeze-test
conda activate bioconda-seabreeze-test
conda install seabreeze-genomics -c conda-forge -c bioconda
```

I was unable to locate an executable named `seabreeze_os_setup` in the directory for the conda environment. 

The `meta.yaml` file for the [seabreeze bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/seabreeze-genomics/meta.yaml) uses `pip` to build seabreeze. See the following excerpt from the recipe:

```
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  entry_points:
    - seabreeze = seabreeze.seabreeze:main
  run_exports:
    - {{ pin_subpackage('seabreeze-genomics', max_pin="x") }}
```

Could you provide some additional information so I can help you?
